### ISSUE TITLE
this package is PURE insanity!!!!!

### ISSUE THREAD

**Issue by randomgambit** [r-lib/vroom#118]
Hi @jimhester this package is insane!!! `vroom` is really super fast!
I tried to load a zipped large file and it merely took a few seconds to unzip and load it.

I have two important questions if you have 2 min. That will help me understand if I can use `vroom` for my large datasets

1. can `vroom` be parallelized? say using the `furrr:future_map()` functions?
2. when unzipping a `zip` file, is `vroom` using the `tmp` directory at all? Or everything happens in memory?

Sorry for taking your time and asking these questions here. I figured I would ask the master himself.

Thanks!!!

**Comment by jimhester** [comment]
Please reserve the issue tracker for actual issues rather than general questions.

1. parallized how? When reading or doing manipulations on the data? The indexing is already multi-threaded.
2. It extracts the compressed file to a temporary directory when indexing, this is cleaned up when the R object is garbage collected.

In the future these sort of questions are a better fit for <https://community.rstudio.com>, please open them there rather than here.
