### ISSUE TITLE
Reading multiple files with the `id` argument compared to `map_dfr` with `.id`

### ISSUE THREAD

**Issue by dieter-wilhelm** [r-lib/vroom#290]
Hello please consider the following:  I'm supplying a vector of multiple path names from `readInput`:

    Files %>% map_dfr(~ vroom(.), .id = "Curve")

I' getting one tibble with the **base names** of the files in the `Curve` column.  Also with the following

    Files %>%  vroom( id = "Curve")

I'm  getting one tibble with a `Curve` column (The terseness is blowing my mind, by the way! :+1: ). But  there're  additionally the **dirnames** in the `Curve`column!  Which is in my opinion a bit overblown from the point of uniqueness and because - in most cases -  the `dirnames()` are identical anyway.  Thank you for vroom!

**Comment by jimhester** [comment]
This is by design, there is no way to know what parts of the path might contain data. For instance it could be 'day-1/report.txt', 'day-2/report.txt' etc. where the directory contains the information instead.

I would suggest using something like the following if you only want the basenames in the output.

```r
library(dplyr)
vroom(Files, id = "Curve") %>% mutate(Curve = basenames(Curve))
```

**Comment by dieter-wilhelm** [comment]
Thank you for your opinion.  I can live with that reasonable argument.  But it seems to me that there are  two different philosophies in the tidyverse and that I wanted to point out.

Please close this "bug" report.  Thanks again for vroom!
